### ISSUE TITLE
email Object of session causing error.

### ISSUE THREAD

**Issue by ChetanBhasin** [countable/dogelet#1]
The default app does not check for undefined 'email' property in sessions and thus produces the following error with the current version.

```
500 TypeError: Cannot read property 'email' of undefined
at app.get.email (/home/chetan/tests/dogelet/app.js:111:24)
at callbacks (/home/chetan/tests/dogelet/node_modules/express/lib/router/index.js:161:37)
at param (/home/chetan/tests/dogelet/node_modules/express/lib/router/index.js:135:11)
at pass (/home/chetan/tests/dogelet/node_modules/express/lib/router/index.js:142:5)
at Router._dispatch (/home/chetan/tests/dogelet/node_modules/express/lib/router/index.js:170:5)
at Object.router (/home/chetan/tests/dogelet/node_modules/express/lib/router/index.js:33:10)
at next (/home/chetan/tests/dogelet/node_modules/express/node_modules/connect/lib/proto.js:190:15)
at Object.EMAIL_REGEX [as handle] (/home/chetan/tests/dogelet/app.js:70:12)
at next (/home/chetan/tests/dogelet/node_modules/express/node_modules/connect/lib/proto.js:190:15)
at Object.methodOverride [as handle] (/home/chetan/tests/dogelet/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:49:5)
```

**Comment by countable** [comment]
Hm, that means your session store isn't initialized. the app currently depends on redis for that. I should probably change it out for a memory store so people can get up and running easier, although it doesn't  preserve logins if you reboot the server. For now you could change to memorystore, or install redis. If you do have redis installed it should work, let me know if it's still an issue.

**Comment by countable** [comment]
To use a memory store isntead of redis just remove that store attribute:

app.use(express.session({secret: 'secretj3902jf'}));

**Comment by ChetanBhasin** [comment]
Sorry for being late on the follow up, but you're right. The error occurs because session store is not initialized.
Thanks for helping with solving the problem. Maybe you can include the information in docs (README.md) file for those who come across this in the future.
